parent=gs-base

gsAppName=GS SMART

gsPrimaryColor=#ED3237
gsPrimaryHoverColor=#D92B30
gsPrimaryActiveColor=#C62529
gsPrimaryColorRgb=237, 50, 55
gsCoverBgColor=#C94A4A

gsSlide1=img/gs/GSSMART2.png
gsSlide2=img/gs/bg2.png
