parent=gs-base

gsAppName=CLAIM

gsPrimaryColor=#6644FF
gsPrimaryHoverColor=#573BE0
gsPrimaryActiveColor=#4A31C2
gsPrimaryColorRgb=102, 68, 255
gsCoverBgColor=#6644FF

# Taruh gambar khusus CLAIM di claim-theme/login/resources/assets/img/gs/
# lalu aktifkan baris di bawah:
gsSlide1=img/gs/claim1.png
gsSlide2=img/gs/claim2.png
#gsBrandIcon=img/gs/claim-icon.png
